#!/bin/bash
HERE="$(dirname "$(readlink -f "$0")")"

export DISPLAY=${DISPLAY:-:0}
export XAUTHORITY=${XAUTHORITY:-$HOME/.Xauthority}
export PYTHONPATH="$HERE/usr/lib/python3.10/site-packages"
export LD_LIBRARY_PATH="$HERE/usr/lib:$HERE/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
export GI_TYPELIB_PATH="$HERE/usr/lib/girepository-1.0"

exec -a "VOSK Dictation" "$HERE/usr/bin/python3" "$HERE/vosk_smal_mod.py"




